// <auto-generated />
using System;
using CocktailOS.Kiosk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CocktailOS.Kiosk.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716193835_AddIngredientInventory")]
    partial class AddIngredientInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CocktailOS.Kiosk.Models.Cocktail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StandardSizeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StandardSizeId");

                    b.ToTable("Cocktails");
                });

            modelBuilder.Entity("CocktailOS.Kiosk.Models.CocktailIngredient", b =>
                {
                    b.Property<int>("CocktailId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountMl")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("CocktailId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CocktailIngredients");
                });

            modelBuilder.Entity("CocktailOS.Kiosk.Models.CocktailSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolumeMl")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("VolumeMl")
                        .IsUnique();

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("CocktailOS.Kiosk.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AlcoholPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BottleSizeMl")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(1000m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemainingVolumeMl")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(1000m);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("CocktailOS.Kiosk.Models.MachineConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinNumberingScheme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PumpDriver")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MachineConfigurations");
                });

            modelBuilder.Entity("CocktailOS.Kiosk.Models.Pump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveHigh")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CalibratedIngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FlowRateMlPerSecond")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowRateSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("manual");

                    b.Property<int>("GpioPin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastCalibratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalibratedIngredientId");

                    b.HasIndex("GpioPin")
                        .IsUnique();

                    b.HasIndex("IngredientId")
                        .IsUnique();

                    b.ToTable("Pumps");
                });

            modelBuilder.Entity("CocktailOS.Kiosk.Models.Cocktail", b =>
                {
                    b.HasOne("CocktailOS.Kiosk.Models.CocktailSize", "StandardSize")
                        .WithMany("StandardForCocktails")
                        .HasForeignKey("StandardSizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StandardSize");
                });

            modelBuilder.Entity("CocktailOS.Kiosk.Models.CocktailIngredient", b =>
                {
                    b.HasOne("CocktailOS.Kiosk.Models.Cocktail", "Cocktail")
                        .WithMany("Ingredients")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CocktailOS.Kiosk.Models.Ingredient", "Ingredient")
                        .WithMany("Cocktails")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cocktail");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CocktailOS.Kiosk.Models.Pump", b =>
                {
                    b.HasOne("CocktailOS.Kiosk.Models.Ingredient", "CalibratedIngredient")
                        .WithMany()
                        .HasForeignKey("CalibratedIngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CocktailOS.Kiosk.Models.Ingredient", "Ingredient")
                        .WithOne("Pump")
                        .HasForeignKey("CocktailOS.Kiosk.Models.Pump", "IngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CalibratedIngredient");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CocktailOS.Kiosk.Models.Cocktail", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CocktailOS.Kiosk.Models.CocktailSize", b =>
                {
                    b.Navigation("StandardForCocktails");
                });

            modelBuilder.Entity("CocktailOS.Kiosk.Models.Ingredient", b =>
                {
                    b.Navigation("Cocktails");

                    b.Navigation("Pump");
                });
#pragma warning restore 612, 618
        }
    }
}
